#!/usr/local/bin/ruby

tellers = `cowsay -l`
tellers = tellers.split("\n")
tellers.delete(tellers.first)
tellers = tellers.first.split(/\s/)
tellers.shuffle!(random: Random.new(1))

programs = ['cowsay', 'cowthink']
system("fortune -as | #{programs.sample} -e eyes -T tongue -f #{tellers.sample}")

