#!env -S ruby -W0
require 'gold_mine'
tellers = `cowsay -l`
tellers = tellers.split("\n")
tellers.delete(tellers.first)
tellers = tellers.first.split(/\s/)
tellers.shuffle!(random: Random.new(1))

fortune = GoldMine::DB.new.random
cmd = %Q(cowsay -f \'#{tellers.sample}\' \"#{fortune.content.delete('"')}\" | lolcat)
system(cmd)

